package com.example.model

data class Rune(
    val name: String,
    val symbol: String,
    val phonetic: String,
    val meaning: String,
    val reversedMeaning: String,
    val element: String
)

data class Hexagram(
    val number: Int,
    val name: String,
    val chineseName: String,
    val trigramUpper: String,
    val trigramLower: String,
    val judgment: String,
    val image: String
)

object RuneData {
    val runes = listOf(
        Rune("Fehu", "ᚠ", "F", "Wealth, abundance, success, financial strength, new beginnings.", "Greed, loss, financial delay, poverty.", "Fire"),
        Rune("Uruz", "ᚢ", "U", "Strength, vitality, courage, health, raw power, untamed potential.", "Weakness, obsession, misdirected force, illness.", "Earth"),
        Rune("Thurisaz", "ᚦ", "Th", "Gateway, protective force, catharsis, breaking through obstacles.", "Danger, defensiveness, betrayal, dullness.", "Fire"),
        Rune("Ansuz", "ᚨ", "A", "Divine communication, wisdom, inspiration, truth, spoken word.", "Misunderstanding, vanity, manipulation, deceit.", "Air"),
        Rune("Raido", "ᚱ", "R", "Journey, travel, rhythm, destiny, right direction, personal growth.", "Stagnation, crisis, dislocation, bad timing.", "Air"),
        Rune("Kenaz", "ᚲ", "K", "Torch, illumination, creativity, technical skill, inner light, revelation.", "Disease, breakup, lack of creativity, illusion.", "Fire"),
        Rune("Gebo", "ᚷ", "G", "Partnership, gifts, generosity, balance, exchange of energy.", "Greed, loneliness, obligation, isolation.", "Air"),
        Rune("Wunjo", "ᚹ", "W", "Joy, fellowship, harmony, emotional satisfaction, success, light.", "Sorrow, discord, alienation, intoxication.", "Earth"),
        Rune("Hagalaz", "ᚺ", "H", "Hail, elemental disruption, radical change, natural forces, trial.", "Disaster, stagnation, loss, suffering.", "Water"),
        Rune("Nauthiz", "ᚾ", "N", "Need, constraint, endurance, self-reliance, overcoming hardship.", "Constraint, toil, starvation, emotional hunger.", "Fire"),
        Rune("Isa", "ᛁ", "I", "Ice, standstill, concentration, self-control, patience, introspection.", "Egoism, dullness, blindness, deceit.", "Water"),
        Rune("Jera", "ᛃ", "J", "Harvest, fruitful season, reward for labor, cycle, peace, justice.", "Major setback, bad timing, poverty, conflict.", "Earth"),
        Rune("Eihwaz", "ᛇ", "Ei", "Yew tree, resilience, reliability, endurance, defense, spiritual growth.", "Confusion, destruction, weakness, dissatisfaction.", "Earth"),
        Rune("Perthro", "ᛈ", "P", "Initiation, mystery, hidden things, fate, chance, occult knowledge.", "Addiction, stagnation, loneliness, illusion.", "Water"),
        Rune("Algiz", "ᛉ", "Z", "Protection, sanctuary, shield, divine connection, higher self guidance.", "Hidden danger, consumption, loss of divine link.", "Air"),
        Rune("Sowilo", "ᛊ", "S", "Sun, success, vitality, wholeness, healing, high energy, victory.", "False goals, bad advice, vanity, wrath, destruction.", "Fire"),
        Rune("Tiwaz", "ᛏ", "T", "Tyr, justice, leadership, honor, sacrifice, strategic victory, truth.", "Injustice, imbalance, over-analysis, waning energy.", "Air"),
        Rune("Berkano", "ᛒ", "B", "Birch, fertility, new growth, regeneration, birth, sanctuary, healing.", "Family problems, domestic trouble, deceit, sterility.", "Earth"),
        Rune("Ehwaz", "ᛖ", "E", "Horse, trust, progress, transportation, partnership, loyalty, teamwork.", "Restlessness, mistrust, disharmony, blocked progress.", "Earth"),
        Rune("Mannaz", "ᛗ", "M", "Humanity, mankind, social order, intelligence, cooperation, self-awareness.", "Depression, mortality, isolation, manipulation.", "Air"),
        Rune("Laguz", "ᛚ", "L", "Water, intuition, flow, emotions, dreams, psychic awareness, the unconscious.", "Fear, circular motion, avoidance, madness, despair.", "Water"),
        Rune("Ingwaz", "ᛜ", "Ng", "Ing, fertility, internal growth, virtues, new life, accomplishment.", "Impotence, movement without purpose, stagnation.", "Earth"),
        Rune("Othala", "ᛟ", "O", "Inheritance, homeland, ancestral heritage, estate, property, core values.", "Total loss, homelessness, bad custom, prejudice.", "Earth"),
        Rune("Dagaz", "ᛞ", "D", "Day, dawn, breakthrough, awakening, transformation, hope, clarity.", "Blindness, hopelessness, completion without renewal, night.", "Fire")
    )
}

object IChingData {
    val hexagrams = listOf(
        Hexagram(1, "The Creative", "Qián", "Heaven", "Heaven", "The Creative works sublime success, furthering through perseverance.", "Heaven moving in strength. The superior person makes themselves strong and untiring."),
        Hexagram(2, "The Receptive", "Kūn", "Earth", "Earth", "The Receptive brings about sublime success, furthering through the persistence of a mare.", "The earth's condition is receptive devotion. The superior person supports all things with broad virtue."),
        Hexagram(3, "Difficulty at the Beginning", "Zhūn", "Water", "Thunder", "Difficulty at the beginning works supreme success, furthering through perseverance.", "Clouds and thunder: Difficulty at the beginning. The superior person brings order out of confusion."),
        Hexagram(4, "Youthful Folly", "Méng", "Mountain", "Water", "Youthful folly has success. It is not I who seek the young fool, the young fool seeks me.", "A spring wells up at the foot of the mountain: Youthful folly. The superior person nourishes character."),
        Hexagram(5, "Waiting (Nourishment)", "Xū", "Water", "Heaven", "Waiting. If you are sincere, you have light and success. Perseverance brings good fortune.", "Clouds rise up to heaven: Waiting. The superior person eats and drinks, rests and is joyous."),
        Hexagram(6, "Conflict", "Sōng", "Heaven", "Water", "Conflict. You are sincere and are obstructed. A cautious halt brings good fortune.", "Heaven and water go their opposite ways: Conflict. The superior person considers well before acting."),
        Hexagram(7, "The Army", "Shī", "Earth", "Water", "The Army. The elder needs perseverance and a strong man. Good fortune without blame.", "Water in the earth: The Army. The superior person nourishes the people by gathering masses."),
        Hexagram(8, "Holding Together", "Bǐ", "Water", "Earth", "Holding together brings good fortune. Inquire of the oracle if you possess primary virtue.", "Water on the earth: Holding together. The kings of antiquity established states and gave security to families."),
        Hexagram(9, "Small Taming", "Xiǎo Xù", "Wind", "Heaven", "Small taming has success. Dense clouds, no rain from our western region.", "The wind blows across heaven: Small taming. The superior person refines outward virtue."),
        Hexagram(10, "Treading (Conduct)", "Lǚ", "Heaven", "Lake", "Treading upon the tail of the tiger. It does not bite the man. Success.", "Heaven above, the lake below: Treading. The superior person discriminates between high and low."),
        Hexagram(11, "Peace", "Tài", "Earth", "Heaven", "Peace. The small departs, the great arrives. Good fortune. Success.", "Heaven and earth unite: Peace. The superior person divides and completes the course of heaven and earth."),
        Hexagram(12, "Standstill (Obstruction)", "Pǐ", "Heaven", "Earth", "Standstill. Evil people do not further the perseverance of the superior person. The great departs, the small arrives.", "Heaven and earth do not unite: Standstill. The superior person withdraws into inner worth."),
        Hexagram(13, "Fellowship with People", "Tóng Rén", "Heaven", "Fire", "Fellowship with people in the open. Success. Furthering to cross the great water.", "Heaven together with fire: Fellowship. The superior person organizes clans and distinguishes things."),
        Hexagram(14, "Great Possession", "Dà Yǒu", "Fire", "Heaven", "Great possession. Supreme success.", "Fire in heaven above: Great possession. The superior person curbs evil and promotes good."),
        Hexagram(15, "Modesty", "Qiān", "Earth", "Mountain", "Modesty creates success. The superior person carries things through.", "Mountains beneath the earth: Modesty. The superior person reduces what is too much and augments what is too little."),
        Hexagram(16, "Enthusiasm", "Yù", "Thunder", "Earth", "Enthusiasm. Furthering to set up helpers and deploy armies.", "Thunder comes booming out of the earth: Enthusiasm. The ancient kings made music to honor merit."),
        Hexagram(17, "Following", "Suí", "Lake", "Thunder", "Following has supreme success. Perseverance furthers. No blame.", "Thunder in the middle of the lake: Following. The superior person at nightfall goes into rest and recuperation."),
        Hexagram(18, "Work on What Has Been Spoiled", "Gǔ", "Mountain", "Wind", "Work on what has been spoiled has supreme success. Furthering to cross the great water.", "Wind blowing low on the mountain: Work on spoiled things. The superior person stirs up the people and nourishes their character."),
        Hexagram(19, "Approach", "Lín", "Earth", "Lake", "Approach has supreme success. Perseverance furthers. When the eighth month comes there will be misfortune.", "The earth above the lake: Approach. The superior person is inexhaustible in teaching and tolerates the people."),
        Hexagram(20, "Contemplation (View)", "Guān", "Wind", "Earth", "Contemplation. The ablution has been made, but not yet the offering. Full of trust they look up to him.", "Wind blowing over the earth: Contemplation. The provincial ruler visits the regions to observe the people."),
        Hexagram(21, "Biting Through", "Shì Hè", "Fire", "Thunder", "Biting through has success. It is favorable to use legal proceedings.", "Thunder and lightning: Biting through. The ancient kings made punishments clear and severe."),
        Hexagram(22, "Grace", "Bì", "Mountain", "Fire", "Grace has success. In small matters it is favorable to undertake something.", "Mountain with fire at the foot: Grace. The superior person clarifies current affairs without daring to decide controversial matters."),
        Hexagram(23, "Splitting Apart", "Bō", "Mountain", "Earth", "Splitting apart. It does not further one to go anywhere.", "Mountain resting on the earth: Splitting apart. Those above can ensure their position only by bestowing gifts."),
        Hexagram(24, "Return (The Turning Point)", "Fù", "Earth", "Thunder", "Return. Success. Going out and coming in without error. Friends come without blame.", "Thunder within the earth: Return. The kings of antiquity closed the passes at the solstice."),
        Hexagram(25, "Innocence (The Unexpected)", "Wú Wàng", "Heaven", "Thunder", "Innocence. Supreme success. Perseverance furthers. If someone is not innocent, they have misfortune.", "Thunder rolls under heaven: Innocence. The ancient kings enriched all creatures in harmony with the season."),
        Hexagram(26, "The Taming Power of the Great", "Dà Xù", "Mountain", "Heaven", "The taming power of the great. Perseverance furthers. Not eating at home brings good fortune.", "Heaven in the mountain: Great Taming. The superior person acquaints themselves with many sayings of antiquity."),
        Hexagram(27, "The Corners of the Mouth (Providing Nourishment)", "Dà Guò", "Lake", "Wind", "The corners of the mouth. Perseverance brings good fortune. Pay heed to the providing of nourishment.", "The thunder shaking the mountain: Nourishment. The superior person is careful of words and temperate in eating and drinking."),
        Hexagram(28, "Preponderance of the Great", "Dà Guò", "Lake", "Wind", "Preponderance of the great. The ridgepole sags. It furthers one to have somewhere to go. Success.", "The lake rises above the trees: Preponderance. The superior person stands alone without fear."),
        Hexagram(29, "The Abyssal (Water)", "Xí Kǎn", "Water", "Water", "The abyssal repeated. If you are sincere, you have success in your heart, and whatever you do succeeds.", "Water flows on continuously: The Abyssal. The superior person abides in constant virtue."),
        Hexagram(30, "The Clinging (Fire)", "Lí", "Fire", "Fire", "The clinging. Perseverance furthers. It brings success. Care of the cow brings good fortune.", "Radiance shining twice: The Clinging. The great person nurtures the illumination of the world."),
        Hexagram(31, "Influence (Wooing)", "Xián", "Lake", "Mountain", "Influence. Success. Perseverance furthers. Taking a maiden to wife brings good fortune.", "Lake on the mountain: Influence. The superior person encourages people by receptivity."),
        Hexagram(32, "Duration", "Héng", "Thunder", "Wind", "Duration. Success. No blame. Perseverance furthers. It furthers one to have somewhere to go.", "Thunder and wind: Duration. The superior person stands firm and does not change direction."),
        Hexagram(33, "Retreat", "Dùn", "Heaven", "Mountain", "Retreat. Success. In small matters, perseverance furthers.", "Mountain under heaven: Retreat. The superior person keeps small-minded people at a distance."),
        Hexagram(34, "The Power of the Great", "Dà Zhuàng", "Thunder", "Heaven", "The power of the great. Perseverance furthers.", "Thunder in heaven above: Power of the Great. The superior person does not step where propriety does not allow."),
        Hexagram(35, "Progress", "Jìn", "Fire", "Earth", "Progress. The powerful prince is honored with horses in large numbers. In a single day he is granted audience three times.", "The sun rises over the earth: Progress. The superior person brightens their bright virtue."),
        Hexagram(36, "Darkening of the Light", "Míng Yí", "Earth", "Fire", "Darkening of the light. In adversity it furthers one to be persevering.", "Light sunk into the earth: Darkening of the Light. The superior person uses dullness to manage the masses."),
        Hexagram(37, "The Family", "Jiā Rén", "Wind", "Fire", "The family. The perseverance of the woman furthers.", "Wind coming forth from fire: The Family. The superior person has substance in words and endurance in way of life."),
        Hexagram(38, "Opposition", "Kuí", "Fire", "Lake", "Opposition. In small matters, good fortune.", "Fire above, lake below: Opposition. The superior person retains individuality amidst commonality."),
        Hexagram(39, "Obstruction", "Jiǎn", "Water", "Mountain", "Obstruction. The southwest furthers, the northeast does not further. It furthers to see the great person.", "Water on the mountain: Obstruction. The superior person turns attention inward to mold character."),
        Hexagram(40, "Deliverance", "Xiè", "Thunder", "Water", "Deliverance. The southwest furthers. If there is nothing where one has to go, return brings good fortune.", "Thunder and rain set in motion: Deliverance. The superior person forgives mistakes and pardons transgressions."),
        Hexagram(41, "Decrease", "Sǔn", "Mountain", "Lake", "Decrease combined with sincerity brings supreme good fortune without blame. One may be persevering in this.", "Mountain below the lake: Decrease. The superior person restrains anger and curbs desires."),
        Hexagram(42, "Increase", "Yì", "Wind", "Thunder", "Increase. It furthers one to undertake something. It furthers one to cross the great water.", "Wind and thunder: Increase. The superior person sees good and imitates it, corrects faults."),
        Hexagram(43, "Breakthrough (Resoluteness)", "Guài", "Lake", "Heaven", "Breakthrough. One must resolutely make the matter known at the king's court. Danger.", "Lake rising up to heaven: Breakthrough. The superior person distributes wealth and favors."),
        Hexagram(44, "Coming to Meet", "Gòu", "Heaven", "Wind", "Coming to meet. The maiden is powerful. One should not marry such a maiden.", "The wind blowing under heaven: Coming to meet. The prince distributes commands to the four quarters."),
        Hexagram(45, "Gathering Together (Massing)", "Cuì", "Lake", "Earth", "Gathering together. Success. The king approaches his temple. It furthers one to see the great person.", "Lake above earth: Gathering Together. The superior person divides weapons to guard against unforeseen events."),
        Hexagram(46, "Pushing Upward", "Shēng", "Earth", "Wind", "Pushing upward has supreme success. One must see the great person. Fear not. Departure toward the south brings good fortune.", "The wood grows upward in the earth: Pushing Upward. The superior person accumulates small things to achieve high character."),
        Hexagram(47, "Oppression (Exhaustion)", "Kùn", "Lake", "Water", "Oppression. Success. Perseverance. The great person brings about good fortune. No blame.", "Lake without water: Oppression. The superior person stakes life upon following the will."),
        Hexagram(48, "The Well", "Jǐng", "Water", "Wind", "The well. The town may be changed, but the well cannot be changed. It neither decreases nor increases.", "Water over wood: The Well. The superior person encourages the people in their work."),
        Hexagram(49, "Revolution (Molting)", "Gé", "Lake", "Fire", "Revolution. On your own day you are believed. Supreme success, furthering through perseverance.", "Fire in the lake: Revolution. The superior person organizes the calendar and clarifies seasons."),
        Hexagram(50, "The Cauldron", "Dǐng", "Fire", "Wind", "The cauldron. Supreme good fortune. Success.", "Fire over wood: The Cauldron. The superior person solidifies fate by aligning character."),
        Hexagram(51, "The Arousing (Shock, Thunder)", "Zhèn", "Thunder", "Thunder", "Shock brings success. Shock comes, oh-oh! Laughing words, ha-ha! The shock terrifies for a hundred miles.", "Thunder repeated: Shock. The superior person reflects and sets life in order."),
        Hexagram(52, "Keeping Still (Mountain)", "Gèn", "Mountain", "Mountain", "Keeping still. Keeping his back still so that he no longer feels his body. No blame.", "Mountain standing still: Keeping Still. The superior person does not let thoughts drift beyond position."),
        Hexagram(53, "Development (Gradual Progress)", "Jiàn", "Wind", "Mountain", "Development. The maiden is given in marriage. Good fortune. Perseverance furthers.", "Tree on the mountain: Development. The superior person abides in dignity and virtue."),
        Hexagram(54, "The Marrying Maiden", "Guī Mèi", "Thunder", "Lake", "The marrying maiden. Undertakings bring misfortune. Nothing that would further.", "Thunder over lake: Marrying Maiden. The superior person understands the transitory in light of eternity."),
        Hexagram(55, "Abundance", "Fēng", "Thunder", "Fire", "Abundance has success. The king attains abundance. Be not sad, be like the sun at noon.", "Thunder and lightning come: Abundance. The superior person decides lawsuits and carries out punishments."),
        Hexagram(56, "The Wanderer", "Lǚ", "Fire", "Mountain", "The wanderer. Success through smallness. Perseverance brings good fortune to the wanderer.", "Fire on the mountain: The Wanderer. The superior person is clear-minded and cautious in lawsuits."),
        Hexagram(57, "The Gentle (Wind, Penetrating)", "Xùn", "Wind", "Wind", "The gentle. Success through smallness. It furthers one to have somewhere to go. It furthers one to see the great person.", "Winds following one another: The Gentle. The superior person spreads commands and carries out affairs."),
        Hexagram(58, "The Joyous (Lake)", "Duì", "Lake", "Lake", "The joyous. Success. Perseverance is favorable.", "Lakes resting one on the other: The Joyous. The superior person joins with friends for discussion and practice."),
        Hexagram(59, "Dispersion (Dissolution)", "Huàn", "Wind", "Water", "Dispersion. Success. The king approaches his temple. It furthers one to cross the great water.", "Wind over water: Dispersion. The kings of antiquity offered sacrifices to the Lord and built temples."),
        Hexagram(60, "Limitation", "Jié", "Water", "Lake", "Limitation. Success. Difficult limitation must not be persevered in.", "Water over lake: Limitation. The superior person creates number and measure, examines virtue."),
        Hexagram(61, "Inner Truth", "Zhōng Fú", "Wind", "Lake", "Inner truth. Pigs and fishes. Good fortune. It furthers one to cross the great water.", "Wind over lake: Inner Truth. The superior person discusses criminal cases in order to delay executions."),
        Hexagram(62, "Preponderance of the Small", "Xiǎo Guò", "Thunder", "Mountain", "Preponderance of the small. Success. Perseverance furthers. Small things may be done, great things may not be done.", "Thunder on the mountain: Preponderance of the Small. The superior person in conduct gives absolute weight to reverence."),
        Hexagram(63, "After Completion", "Jì Jì", "Water", "Fire", "After completion. Success in small matters. Perseverance furthers. At the beginning good fortune, at the end disorder.", "Water over fire: After completion. The superior person takes thought of misfortune and arms against it in advance."),
        Hexagram(64, "Before Completion", "Wēi Jì", "Fire", "Water", "Before completion. Success. But if the little fox, nearly crossing, gets its tail in the water, nothing is furthered.", "Fire over water: Before completion. The superior person is careful in distinguishing things so that each finds its place.")
    )
}
