package com.example.model

data class TarotCard(
    val id: Int = 0,
    val name: String,
    val arcana: String, // "Major" or "Minor"
    val suit: String?, // "Wands", "Cups", "Swords", "Pentacles", or null for Major
    val uprightMeaning: String,
    val reversedMeaning: String,
    val description: String,
    val astrology: String,
    val numerology: String,
    val element: String,
    val planet: String,
    val symbology: List<String>,
    val defaultTerms: List<String>
)

object TarotData {
    val defaultCards: List<TarotCard> = listOf(
        TarotCard(
            name = "0. The Fool",
            arcana = "Major",
            suit = null,
            uprightMeaning = "New beginnings, innocence, spontaneity, a free spirit.",
            reversedMeaning = "Naivety, foolishness, recklessness, risk-taking.",
            description = "A young traveler stepping off a cliff with complete faith in the universe.",
            astrology = "Aquarius",
            numerology = "0",
            element = "Air",
            planet = "Uranus",
            symbology = listOf("White Dog (Loyalty/Instinct)", "Cliff (Leap of Faith)", "Sun (Vitality)", "Knapsack (Preparedness)"),
            defaultTerms = listOf("Beginnings", "Spontaneity", "Potential", "Innocence", "Leap of Faith")
        ),
        TarotCard(
            name = "I. The Magician",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Manifestation, resourcefulness, power, inspired action.",
            reversedMeaning = "Manipulation, poor planning, untapped talents.",
            description = "A master of elements standing before an altar with tools of creation.",
            astrology = "Gemini / Virgo",
            numerology = "I",
            element = "Air",
            planet = "Mercury",
            symbology = listOf("Infinity Symbol (Eternal Power)", "Wand (Willpower)", "Four Elements (Cups, Pentacles, Swords, Wands)", "Red Roses & White Lilies"),
            defaultTerms = listOf("Manifestation", "Willpower", "Creation", "Skill", "Resourcefulness")
        ),
        TarotCard(
            name = "II. The High Priestess",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Intuition, sacred knowledge, divine feminine, subconscious.",
            reversedMeaning = "Secrets, disconnected intuition, superficiality.",
            description = "A veiled figure seated between pillars of light and darkness.",
            astrology = "Cancer",
            numerology = "II",
            element = "Water",
            planet = "Moon",
            symbology = listOf("Pillars J & B (Dualism)", "Pomegranate Veil (Fertility & Mystery)", "Scroll of Torah", "Crescent Moon"),
            defaultTerms = listOf("Intuition", "Subconscious", "Mystery", "Inner Voice", "Divine Feminine")
        ),
        TarotCard(
            name = "III. The Empress",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Femininity, beauty, nature, nurturing, abundance.",
            reversedMeaning = "Creative block, dependence on others, emptiness.",
            description = "A majestic queen surrounded by golden wheat fields and cascading waterfalls.",
            astrology = "Taurus / Libra",
            numerology = "III",
            element = "Earth",
            planet = "Venus",
            symbology = listOf("Venus Symbol", "Wheat Field (Harvest)", "Star Crown (12 Stars)", "Waterfall & Forest"),
            defaultTerms = listOf("Abundance", "Nurturing", "Nature", "Fertility", "Creativity")
        ),
        TarotCard(
            name = "IV. The Emperor",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Authority, structure, control, father figure, establishment.",
            reversedMeaning = "Tyranny, rigidity, coldness, lack of discipline.",
            description = "A stern ruler seated on a stone throne adorned with ram heads.",
            astrology = "Aries",
            numerology = "IV",
            element = "Fire",
            planet = "Mars",
            symbology = listOf("Ram Heads (Aries/Leadership)", "Stone Throne (Stability)", "Globe of Dominion", "Mountains"),
            defaultTerms = listOf("Authority", "Structure", "Leadership", "Stability", "Control")
        ),
        TarotCard(
            name = "V. The Hierophant",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Spiritual wisdom, religious beliefs, conformity, tradition, institutions.",
            reversedMeaning = "Personal beliefs, rebellion, unorthodox approaches.",
            description = "A spiritual teacher bestowing blessings in a sacred temple.",
            astrology = "Taurus",
            numerology = "V",
            element = "Earth",
            planet = "Venus / Jupiter",
            symbology = listOf("Triple Crown", "Crossed Keys", "Two Acolytes", "Pillars of the Temple"),
            defaultTerms = listOf("Tradition", "Spiritual Wisdom", "Guidance", "Institutions", "Beliefs")
        ),
        TarotCard(
            name = "VI. The Lovers",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Love, harmony, vital relationships, values alignment, choices.",
            reversedMeaning = "Disharmony, imbalance, misaligned values, bad choices.",
            description = "Two souls standing under the blessing of an angelic figure in Eden.",
            astrology = "Gemini",
            numerology = "VI",
            element = "Air",
            planet = "Mercury",
            symbology = listOf("Angel Raphael (Healing)", "Tree of Life & Knowledge", "The Serpent", "Mountain of Ascension"),
            defaultTerms = listOf("Love", "Harmonious Union", "Choices", "Values", "Partnership")
        ),
        TarotCard(
            name = "VII. The Chariot",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Control, willpower, success, action, determination, overcoming obstacles.",
            reversedMeaning = "Lack of control, opposition, directionless wandering.",
            description = "A victorious warrior steering a chariot pulled by sphinxes of will.",
            astrology = "Cancer",
            numerology = "VII",
            element = "Water",
            planet = "Moon",
            symbology = listOf("Black & White Sphinxes (Duality)", "Canopy of Stars", "Wand of Power", "Armor of Protection"),
            defaultTerms = listOf("Victory", "Willpower", "Drive", "Determination", "Focus")
        ),
        TarotCard(
            name = "VIII. Strength",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Courage, compassion, inner power, patience, gentle control.",
            reversedMeaning = "Self-doubt, raw emotion, weakness, lack of confidence.",
            description = "A calm figure gently closing the jaws of a majestic lion.",
            astrology = "Leo",
            numerology = "VIII",
            element = "Fire",
            planet = "Sun",
            symbology = listOf("Infinity Lemniscate", "The Lion (Passion/Ego)", "Garland of Flowers", "Serene Woman"),
            defaultTerms = listOf("Courage", "Compassion", "Inner Strength", "Patience", "Resilience")
        ),
        TarotCard(
            name = "IX. The Hermit",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Soul-searching, introspection, solitude, inner guidance, wisdom.",
            reversedMeaning = "Isolation, loneliness, withdrawal, lost direction.",
            description = "An old sage holding a glowing lantern high on a snowy mountain peak.",
            astrology = "Virgo",
            numerology = "IX",
            element = "Earth",
            planet = "Mercury",
            symbology = listOf("Lantern of Truth (Solomon's Seal)", "Staff of Authority", "Snowy Mountain", "Solitude"),
            defaultTerms = listOf("Introspection", "Solitude", "Inner Guidance", "Wisdom", "Soul-Searching")
        ),
        TarotCard(
            name = "X. Wheel of Fortune",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Good luck, karma, life cycles, destiny, turning point, inevitability.",
            reversedMeaning = "Bad luck, negative cycles, resistance to change.",
            description = "A cosmic wheel turning through epochs with figures of fate ascending and descending.",
            astrology = "Jupiter",
            numerology = "X",
            element = "Fire",
            planet = "Jupiter",
            symbology = listOf("Sphinx of Wisdom", "Anubis & Typhon", "Hebrew Letters (YHWH)", "Four Winged Evangels"),
            defaultTerms = listOf("Destiny", "Karma", "Turning Point", "Cycles", "Fortune")
        ),
        TarotCard(
            name = "XI. Justice",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Fairness, truth, cause and effect, law, clarity, accountability.",
            reversedMeaning = "Dishonesty, unfairness, lack of accountability, bias.",
            description = "An impartial judge holding the scales of truth and a double-edged sword.",
            astrology = "Libra",
            numerology = "XI",
            element = "Air",
            planet = "Venus",
            symbology = listOf("Scales of Balance", "Double-Edged Sword", "Red Cape & Crown", "Pillar of Law"),
            defaultTerms = listOf("Justice", "Truth", "Fairness", "Accountability", "Law")
        ),
        TarotCard(
            name = "XII. The Hanged Man",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Surrender, pause, new perspective, letting go, enlightenment.",
            reversedMeaning = "Stalling, needless sacrifice, fear of sacrifice.",
            description = "A serene figure suspended upside down from a living wooden cross.",
            astrology = "Neptune / Pisces",
            numerology = "XII",
            element = "Water",
            planet = "Neptune",
            symbology = listOf("Halo of Enlightenment", "T-Cross of Living Wood", "Suspended Posture", "Serene Expression"),
            defaultTerms = listOf("Surrender", "New Perspective", "Release", "Pause", "Enlightenment")
        ),
        TarotCard(
            name = "XIII. Death",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Transformation, endings, transition, rebirth, shedding the old.",
            reversedMeaning = "Resistance to change, stagnation, fear of inevitable endings.",
            description = "An armored skeleton riding a white horse across a threshold of sun and dawn.",
            astrology = "Scorpio",
            numerology = "XIII",
            element = "Water",
            planet = "Pluto",
            symbology = listOf("Armored Skeleton", "White Horse", "Rising Sun between Towers", "Mystic Rose Flag"),
            defaultTerms = listOf("Transformation", "Rebirth", "Endings", "Transition", "Renewal")
        ),
        TarotCard(
            name = "XIV. Temperance",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Balance, moderation, patience, purpose, divine timing, harmony.",
            reversedMeaning = "Imbalance, excess, clashing energies, lack of patience.",
            description = "An angelic being pouring fluid between two golden chalices with perfect balance.",
            astrology = "Sagittarius",
            numerology = "XIV",
            element = "Fire",
            planet = "Jupiter",
            symbology = listOf("Angel with Wings", "Two Golden Chalices", "One Foot in Water, One on Land", "Path to Mountains"),
            defaultTerms = listOf("Balance", "Moderation", "Harmony", "Patience", "Alchemy")
        ),
        TarotCard(
            name = "XV. The Devil",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Shadow self, attachment, addiction, restriction, materialism.",
            reversedMeaning = "Freedom, reclaiming power, overcoming addiction, release.",
            description = "Bound figures standing before a horned deity of worldly illusion.",
            astrology = "Capricorn",
            numerology = "XV",
            element = "Earth",
            planet = "Saturn",
            symbology = listOf("Baphomet / Horned God", "Loose Chains on Figures", "Inverted Pentagram", "Torch of Illusions"),
            defaultTerms = listOf("Shadow Self", "Attachment", "Bondage", "Materialism", "Liberation")
        ),
        TarotCard(
            name = "XVI. The Tower",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Sudden change, upheaval, revelation, awakening, breaking illusions.",
            reversedMeaning = "Disaster avoided, delayed trauma, fear of suffering.",
            description = "Lightning striking a stone tower as flames burst from the windows.",
            astrology = "Mars",
            numerology = "XVI",
            element = "Fire",
            planet = "Mars",
            symbology = listOf("Lightning Bolt (Divine Strike)", "Falling Crown", "Burning Tower", "Yot Flames"),
            defaultTerms = listOf("Upheaval", "Revelation", "Sudden Change", "Awakening", "Breakthrough")
        ),
        TarotCard(
            name = "XVII. The Star",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Hope, faith, purpose, renewal, inspiration, spiritual blessing.",
            reversedMeaning = "Despair, lack of faith, discouragement, pessimism.",
            description = "A celestial maiden pouring healing waters into a serene starlit pool.",
            astrology = "Aquarius",
            numerology = "XVII",
            element = "Air",
            planet = "Uranus",
            symbology = listOf("8-Pointed Star of Venus", "Two Urns of Water", "Naked Figure (Vulnerability)", "Ibis Bird"),
            defaultTerms = listOf("Hope", "Faith", "Inspiration", "Renewal", "Healing")
        ),
        TarotCard(
            name = "XVIII. The Moon",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Illusion, fear, anxiety, subconscious, intuition, dreams, uncertainty.",
            reversedMeaning = "Release of fear, repressed emotion surfacing, clarity dawning.",
            description = "A mystical night landscape illuminated by a crescent moon and howling wolves.",
            astrology = "Pisces",
            numerology = "XVIII",
            element = "Water",
            planet = "Neptune",
            symbology = listOf("Crescent Moon with Face", "Dog and Wolf (Tame/Wild Nature)", "Crawling Crayfish", "Two Towers"),
            defaultTerms = listOf("Illusion", "Dreams", "Subconscious", "Fear", "Intuition")
        ),
        TarotCard(
            name = "XIX. The Sun",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Joy, success, celebration, vitality, positivity, warmth, clarity.",
            reversedMeaning = "Temporary sadness, overly optimistic view, clouded joy.",
            description = "A radiant golden sun shining down upon a joyful child riding a white horse.",
            astrology = "Sun",
            numerology = "XIX",
            element = "Fire",
            planet = "Sun",
            symbology = listOf("Radiant Sun with Face", "Naked Child (Innocence)", "White Horse of Purity", "Sunflower Garden"),
            defaultTerms = listOf("Joy", "Success", "Vitality", "Optimism", "Clarity")
        ),
        TarotCard(
            name = "XX. Judgement",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Rebirth, inner calling, absolution, awakening, reckoning, forgiveness.",
            reversedMeaning = "Self-doubt, harsh self-judgment, ignoring the call.",
            description = "An angelic trumpet sounding as figures rise joyfully from earthly graves.",
            astrology = "Pluto",
            numerology = "XX",
            element = "Fire",
            planet = "Pluto",
            symbology = listOf("Archangel Gabriel", "Trumpet of Awakening", "Rising Figures from Coffins", "Mountains of Eternity"),
            defaultTerms = listOf("Rebirth", "Awakening", "Calling", "Absolution", "Judgment")
        ),
        TarotCard(
            name = "XXI. The World",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Completion, accomplishment, travel, wholeness, fulfillment, unity.",
            reversedMeaning = "Lack of closure, unfinished business, delays in success.",
            description = "A dancing figure framed by a laurel wreath surrounded by the four cosmic guardians.",
            astrology = "Saturn",
            numerology = "XXI",
            element = "Earth",
            planet = "Saturn",
            symbology = listOf("Laurel Wreath of Victory", "Dancing Hermaphrodite", "Four Evangelists (Bull, Lion, Eagle, Angel)", "Wands of Power"),
            defaultTerms = listOf("Completion", "Wholeness", "Achievement", "Fulfillment", "Unity")
        ),
        // --- SUIT OF WANDS (FIRE) ---
        TarotCard(
            name = "Ace of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Inspiration, creative spark, new opportunity, passion, vitality.",
            reversedMeaning = "Delays, lack of motivation, creative block, missed potential.",
            description = "A divine hand emerges from a cloud holding a budding wooden wand bursting with life.",
            astrology = "Aries / Leo / Sagittarius",
            numerology = "1",
            element = "Fire",
            planet = "Mars / Sun",
            symbology = listOf("Hand of God", "Sprouting Wand", "Falling Yod Leaves", "Distant Castle"),
            defaultTerms = listOf("Inspiration", "Power", "Creation", "Courage", "Drive")
        ),
        TarotCard(
            name = "Two of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Future planning, progress, decisions, stepping out of comfort zones.",
            reversedMeaning = "Fear of the unknown, bad planning, over-analyzing, feeling confined.",
            description = "A wealthy merchant holds a miniature globe from a castle rampart, contemplating his domain.",
            astrology = "Mars in Aries",
            numerology = "2",
            element = "Fire",
            planet = "Mars",
            symbology = listOf("Terrestrial Globe", "Castle Parapet", "Two Flowering Staves", "Ships at Sea"),
            defaultTerms = listOf("Planning", "Vision", "Expansion", "Discovery", "Ambition")
        ),
        TarotCard(
            name = "Three of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Expansion, overseas exploration, foresight, enterprise, confidence.",
            reversedMeaning = "Delays, roadblocks, disappointment, unexpected setbacks.",
            description = "A traveler looks out over the ocean as merchant ships navigate golden sunset waters.",
            astrology = "Sun in Aries",
            numerology = "3",
            element = "Fire",
            planet = "Sun",
            symbology = listOf("Three Firmly Planted Staves", "Golden Ships", "Distant Mountains", "Traveler Cloak"),
            defaultTerms = listOf("Exploration", "Expansion", "Opportunity", "Foresight", "Enterprise")
        ),
        TarotCard(
            name = "Four of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Celebration, homecoming, harmony, community, milestones, domestic bliss.",
            reversedMeaning = "Personal celebration, inner harmony, tension among family, cancelled events.",
            description = "A joyful couple lifts flower garlands beneath a sacred four-pillared canopy outside a manor.",
            astrology = "Venus in Aries",
            numerology = "4",
            element = "Fire",
            planet = "Venus",
            symbology = listOf("Garland of Flowers & Grapes", "Four Staves Arbour", "Moated Castle", "Joyous Community"),
            defaultTerms = listOf("Celebration", "Homecoming", "Harmony", "Community", "Peace")
        ),
        TarotCard(
            name = "Five of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Competition, discord, conflict, rivalry, diverse opinions, testing one's skill.",
            reversedMeaning = "Conflict avoidance, finding common ground, resolution, fatigue.",
            description = "Five youths brandish wooden staves in energetic mock combat, each facing a different direction.",
            astrology = "Saturn in Leo",
            numerology = "5",
            element = "Fire",
            planet = "Saturn",
            symbology = listOf("Five Clash Staves", "Uncoordinated Youth", "Colorful Tunics", "Uneven Ground"),
            defaultTerms = listOf("Competition", "Rivalry", "Struggle", "Tension", "Challenge")
        ),
        TarotCard(
            name = "Six of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Victory, success, public acclaim, pride, recognition, breakthrough.",
            reversedMeaning = "Egotism, fall from grace, lack of recognition, private achievement.",
            description = "A victorious rider on a draped white steed passes through a cheering crowd with a laurel wreath.",
            astrology = "Jupiter in Leo",
            numerology = "6",
            element = "Fire",
            planet = "Jupiter",
            symbology = listOf("Laurel Wreath of Victory", "White Caparisoned Steed", "Cheering Footmen", "Upright Staff"),
            defaultTerms = listOf("Victory", "Acclaim", "Honor", "Triumph", "Confidence")
        ),
        TarotCard(
            name = "Seven of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Defense, perseverance, standing one's ground, courage under pressure.",
            reversedMeaning = "Exhaustion, giving in, overwhelmed, admitting defeat.",
            description = "A valiant defender on high ground fends off six attacking staves with singular resolve.",
            astrology = "Mars in Leo",
            numerology = "7",
            element = "Fire",
            planet = "Mars",
            symbology = listOf("High Ground Advantage", "Mismatched Shoes", "Defensive Staff", "Six Lower Staves"),
            defaultTerms = listOf("Courage", "Perseverance", "Defiance", "Integrity", "Resilience")
        ),
        TarotCard(
            name = "Eight of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Rapid movement, swift action, incoming messages, travel, alignment.",
            reversedMeaning = "Delays, frustration, hasty panic, miscommunication, resisting pace.",
            description = "Eight flowering wooden staves soar cleanly through open sky toward green fields below.",
            astrology = "Mercury in Sagittarius",
            numerology = "8",
            element = "Fire",
            planet = "Mercury",
            symbology = listOf("Eight Swift Staves", "Clear Sky", "Meandering River", "Peaceful Hillside"),
            defaultTerms = listOf("Speed", "Momentum", "Action", "Travel", "Flow")
        ),
        TarotCard(
            name = "Nine of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Resilience, grit, final defense, vigilance, endurance, boundaries.",
            reversedMeaning = "Defensive exhaustion, paranoia, burnout, refusing help.",
            description = "A bandaged guard leans on his sturdy staff, eyeing the perimeter against future trials.",
            astrology = "Moon in Sagittarius",
            numerology = "9",
            element = "Fire",
            planet = "Moon",
            symbology = listOf("Head Bandage", "Wall of Eight Staves", "Guarded Staff", "Vigilant Eye"),
            defaultTerms = listOf("Resilience", "Vigilance", "Endurance", "Boundaries", "Strength")
        ),
        TarotCard(
            name = "Ten of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Heavy burden, over-extension, duty, relentless labor, nearing finish line.",
            reversedMeaning = "Carrying too much, collapse, delegating, releasing unnecessary weight.",
            description = "A weary worker strains under the weight of ten bundled heavy staves toward a nearby town.",
            astrology = "Saturn in Sagittarius",
            numerology = "10",
            element = "Fire",
            planet = "Saturn",
            symbology = listOf("Heavy Bundle of Ten Staves", "Bent Spine", "Visible Destination Town", "Plowed Earth"),
            defaultTerms = listOf("Burden", "Responsibility", "Overwork", "Stress", "Perseverance")
        ),
        TarotCard(
            name = "Page of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Enthusiasm, creative sparks, free spirit, messenger of adventure, youth.",
            reversedMeaning = "Unchanneled zeal, scattered ideas, insecurity, hasty missteps.",
            description = "A spirited youth stands in a desert gaze, holding a staff sprouting green foliage.",
            astrology = "Earth of Fire",
            numerology = "Page",
            element = "Fire",
            planet = "Sun",
            symbology = listOf("Salamander Patterned Tunic", "Feather in Cap", "Desert Pyramids", "Sprouting Wand"),
            defaultTerms = listOf("Enthusiasm", "Discovery", "Curiosity", "Courage", "Messages")
        ),
        TarotCard(
            name = "Knight of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Action, fiery passion, adventure, audacity, daring confidence.",
            reversedMeaning = "Recklessness, impatience, erratic outbursts, temperamental haste.",
            description = "An armored knight on a galloping chestnut stallion charges forward with fiery vigor.",
            astrology = "Fire of Fire",
            numerology = "Knight",
            element = "Fire",
            planet = "Mars",
            symbology = listOf("Galloping Stallion", "Flamboyant Feather Plume", "Full Plate Armor", "Arid Dunes"),
            defaultTerms = listOf("Passion", "Adventure", "Impulse", "Audacity", "Speed")
        ),
        TarotCard(
            name = "Queen of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Warmth, magnetic charisma, confidence, fertility, creative mastery.",
            reversedMeaning = "Demanding, jealousy, self-doubt, hidden insecurity, shrinking back.",
            description = "A radiant queen sits on a lion-carved throne holding a golden sunflower and sprouting wand.",
            astrology = "Water of Fire",
            numerology = "Queen",
            element = "Fire",
            planet = "Sun / Venus",
            symbology = listOf("Black Cat (Intuition)", "Golden Sunflower", "Lion Throne Carvings", "Regal Stare"),
            defaultTerms = listOf("Charisma", "Confidence", "Warmth", "Creativity", "Vitality")
        ),
        TarotCard(
            name = "King of Wands",
            arcana = "Minor",
            suit = "Wands",
            uprightMeaning = "Visionary leader, entrepreneurship, honor, inspiring force, authority.",
            reversedMeaning = "Impatience, domineering ego, intolerance, unrealistic demands.",
            description = "A powerful king with a crown of flames holds an upright flowering staff atop a lion throne.",
            astrology = "Air of Fire",
            numerology = "King",
            element = "Fire",
            planet = "Jupiter / Mars",
            symbology = listOf("Crown of Fire", "Salamander Biting Tail", "Lions and Serpents", "Robes of Orange and Gold"),
            defaultTerms = listOf("Leadership", "Vision", "Honor", "Inspiration", "Authority")
        ),

        // --- SUIT OF CUPS (WATER) ---
        TarotCard(
            name = "Ace of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Unconditional love, emotional renewal, intuition, spiritual blessing.",
            reversedMeaning = "Blocked feelings, emotional draining, self-neglect, withheld love.",
            description = "A radiant chalice overflowing with five streams of living water fed by a divine dove.",
            astrology = "Cancer / Scorpio / Pisces",
            numerology = "1",
            element = "Water",
            planet = "Moon / Neptune",
            symbology = listOf("Golden Chalice", "Dove with Eucharist", "Five Overflow Streams", "Water Lilies"),
            defaultTerms = listOf("Love", "Compassion", "Intuition", "Overflow", "Spiritual Blessing")
        ),
        TarotCard(
            name = "Two of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Soulmate connection, mutual respect, sacred union, romantic harmony.",
            reversedMeaning = "Imbalance, broken communication, codependency, tension.",
            description = "Two partners exchange golden chalices beneath the winged Caduceus of Hermes and a lion head.",
            astrology = "Venus in Cancer",
            numerology = "2",
            element = "Water",
            planet = "Venus",
            symbology = listOf("Caduceus of Hermes", "Winged Lion Head", "Exchanged Chalices", "Laurel & Flower Wreaths"),
            defaultTerms = listOf("Partnership", "Harmony", "Union", "Attraction", "Trust")
        ),
        TarotCard(
            name = "Three of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Sisterhood, friendship, communal celebration, creative synergy, joy.",
            reversedMeaning = "Gossip, excluded feelings, overindulgence, superficial company.",
            description = "Three graceful maidens toast their raised golden cups together in an orchard garden.",
            astrology = "Mercury in Cancer",
            numerology = "3",
            element = "Water",
            planet = "Mercury",
            symbology = listOf("Three Raised Chalices", "Harvest Fruits", "Intertwined Arms", "Flowing Garments"),
            defaultTerms = listOf("Celebration", "Friendship", "Synergy", "Rejoicing", "Community")
        ),
        TarotCard(
            name = "Four of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Contemplation, apathy, meditation, withdrawal, re-evaluating emotional desires.",
            reversedMeaning = "Awakening, renewed enthusiasm, accepting offers, gratitude.",
            description = "A seated youth sits beneath a tree with crossed arms, ignoring an offering cup held from a cloud.",
            astrology = "Moon in Cancer",
            numerology = "4",
            element = "Water",
            planet = "Moon",
            symbology = listOf("Crossed Arms", "Floating Cup in Cloud", "Three Ground Cups", "Grounded Shade Tree"),
            defaultTerms = listOf("Apathy", "Contemplation", "Re-evaluation", "Introspection", "Discontent")
        ),
        TarotCard(
            name = "Five of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Grief, regret, focusing on loss, emotional disappointment, mourning.",
            reversedMeaning = "Acceptance, moving forward, healing emotional wounds, noticing hope.",
            description = "A black-cloaked figure gazes mournfully at three spilled cups while two remain intact behind.",
            astrology = "Mars in Scorpio",
            numerology = "5",
            element = "Water",
            planet = "Mars",
            symbology = listOf("Three Spilled Cups", "Two Upright Cups", "Black Mourning Cloak", "River Bridge to Sanctuary"),
            defaultTerms = listOf("Grief", "Loss", "Regret", "Disappointment", "Healing")
        ),
        TarotCard(
            name = "Six of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Nostalgia, childhood memories, innocent kindness, reunions, purity.",
            reversedMeaning = "Living in the past, childish clinginess, moving on from childhood.",
            description = "A young boy kindly offers a flower-filled cup to a younger girl outside an ancient castle.",
            astrology = "Sun in Scorpio",
            numerology = "6",
            element = "Water",
            planet = "Sun",
            symbology = listOf("Cups Filled with White Flowers", "Ancient Stone Garden", "Departing Guard", "Childhood Innocence"),
            defaultTerms = listOf("Nostalgia", "Innocence", "Reunion", "Kindness", "Memories")
        ),
        TarotCard(
            name = "Seven of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Illusion, wishful thinking, endless possibilities, fantasy, daydreams.",
            reversedMeaning = "Clarity, selecting true path, overcoming illusion, realism.",
            description = "A silhouette stands before clouds of seven floating cups bearing jewels, monsters, and crowns.",
            astrology = "Venus in Scorpio",
            numerology = "7",
            element = "Water",
            planet = "Venus",
            symbology = listOf("Snake, Laurel, Castle, Dragon, Jewels, Mask, Radiant Figure", "Floating Clouds"),
            defaultTerms = listOf("Choices", "Fantasy", "Illusion", "Desire", "Discernment")
        ),
        TarotCard(
            name = "Eight of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Walking away, seeking higher truth, leaving what no longer serves, spiritual quest.",
            reversedMeaning = "Fear of change, stagnation, lingering in bad situations, return.",
            description = "A robed traveler turns his back on eight stacked cups to hike by moonlight into high mountains.",
            astrology = "Saturn in Pisces",
            numerology = "8",
            element = "Water",
            planet = "Saturn",
            symbology = listOf("Stacked Cups with Missing Gap", "Traveler Staff", "Eclipse Moon", "Stony Ascent"),
            defaultTerms = listOf("Walking Away", "Quest", "Release", "Deeper Meaning", "Transcendence")
        ),
        TarotCard(
            name = "Nine of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Wish fulfillment, contentment, luxury, emotional satisfaction, gratitude.",
            reversedMeaning = "Smugness, over-indulgence, superficial pride, unfilled wishes.",
            description = "A satisfied host sits comfortably with folded arms before an arched semicircular display of nine golden cups.",
            astrology = "Jupiter in Pisces",
            numerology = "9",
            element = "Water",
            planet = "Jupiter",
            symbology = listOf("Nine Golden Cups on Semicircular Drapes", "Folded Arms of Contentment", "Feast Tunic"),
            defaultTerms = listOf("Contentment", "Satisfaction", "Gratitude", "Wishes Fulfilled", "Abundance")
        ),
        TarotCard(
            name = "Ten of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Divine harmony, family bliss, emotional fulfillment, peace, lasting joy.",
            reversedMeaning = "Domestic discord, shattered expectations, strained relationships, broken vows.",
            description = "A loving couple gestures joyously toward a heavenly rainbow of ten golden cups as children play.",
            astrology = "Mars in Pisces",
            numerology = "10",
            element = "Water",
            planet = "Jupiter / Neptune",
            symbology = listOf("Rainbow of Ten Cups", "Dancing Children", "Embracing Couple", "Homestead and River"),
            defaultTerms = listOf("Family Bliss", "Harmony", "Fulfillment", "Peace", "Divine Love")
        ),
        TarotCard(
            name = "Page of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Intuitive whispers, poetic imagination, innocent heart, sweet surprises.",
            reversedMeaning = "Emotional fragility, insecurity, escapism, creative blocks.",
            description = "A gentle youth by the shore admires a curious blue fish peeking out of his golden chalice.",
            astrology = "Earth of Water",
            numerology = "Page",
            element = "Water",
            planet = "Moon",
            symbology = listOf("Fish Emerging from Chalice", "Lotus Flowered Tunic", "Gentle Waves", "Poetic Beret"),
            defaultTerms = listOf("Curiosity", "Intuition", "Imagination", "Innocence", "Surprise")
        ),
        TarotCard(
            name = "Knight of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Romantic chivalry, artistic messenger, following the heart, poetic quest.",
            reversedMeaning = "Moodiness, unrealistic romanticism, passive-aggressive drama, fickleness.",
            description = "A quiet knight rides a calm gray steed across a serene river, bearing a golden cup like a holy grail.",
            astrology = "Fire of Water",
            numerology = "Knight",
            element = "Water",
            planet = "Venus",
            symbology = listOf("Winged Helmet & Heels", "Calm River Steed", "Fish Decorated Tunic", "Tender Demeanor"),
            defaultTerms = listOf("Romance", "Chivalry", "Artistry", "Heart", "Elegance")
        ),
        TarotCard(
            name = "Queen of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Deep empathy, psychic intuition, emotional healer, compassionate heart.",
            reversedMeaning = "Co-dependency, emotional burnout, martyrdom, mood swings.",
            description = "An intuitive queen sits by the tides gazing deeply into an intricate, lidded vessel of mysteries.",
            astrology = "Water of Water",
            numerology = "Queen",
            element = "Water",
            planet = "Moon / Neptune",
            symbology = listOf("Elaborate Closed Chalice", "Shell & Mermaid Throne", "Water Kissing Robes", "Psychic Depth"),
            defaultTerms = listOf("Empathy", "Intuition", "Healing", "Compassion", "Depth")
        ),
        TarotCard(
            name = "King of Cups",
            arcana = "Minor",
            suit = "Cups",
            uprightMeaning = "Emotional balance, wise counselor, compassion, calm leadership, dignity.",
            reversedMeaning = "Manipulation, emotional coldness, suppressed volatile rage, deception.",
            description = "A bearded sovereign sits on a stone throne floating upon the open sea, calm amidst surging waves.",
            astrology = "Air of Water",
            numerology = "King",
            element = "Water",
            planet = "Jupiter / Neptune",
            symbology = listOf("Floating Throne on Waves", "Leaping Fish & Ship", "Fish Amulet", "Calm Scepter"),
            defaultTerms = listOf("Emotional Wisdom", "Calm", "Diplomacy", "Compassion", "Integrity")
        ),

        // --- SUIT OF SWORDS (AIR) ---
        TarotCard(
            name = "Ace of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Mental breakthrough, absolute truth, clarity, piercing intellect, triumph.",
            reversedMeaning = "Hostility, clouded judgment, harsh words, misinformation, cruelty.",
            description = "A divine hand from a cloud holds aloft a double-edged sword encircled by a golden crown and olive branches.",
            astrology = "Gemini / Libra / Aquarius",
            numerology = "1",
            element = "Air",
            planet = "Mercury / Mars",
            symbology = listOf("Double-Edged Sword", "Golden Crown", "Olive & Palm Branches", "Mountain Peaks"),
            defaultTerms = listOf("Breakthrough", "Clarity", "Truth", "Intellect", "Triumph")
        ),
        TarotCard(
            name = "Two of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Difficult decision, stalemate, weighing two choices, truce, calm reflection.",
            reversedMeaning = "Indecision, emotional overwhelm, falsehood revealed, deadlock.",
            description = "A blindfolded figure sits in white robes by the sea, holding two heavy swords crossed in balance.",
            astrology = "Moon in Libra",
            numerology = "2",
            element = "Air",
            planet = "Moon",
            symbology = listOf("Blindfold (Impartiality)", "Crossed Swords in Balance", "Crescent Moon", "Rocky Shoals"),
            defaultTerms = listOf("Stalemate", "Decision", "Truce", "Balance", "Intellect")
        ),
        TarotCard(
            name = "Three of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Heartbreak, emotional grief, sorrow, painful revelation, release of tears.",
            reversedMeaning = "Recovery from grief, forgiveness, releasing old wounds, optimism returning.",
            description = "A crimson heart is pierced by three swords beneath a storm-swept sky of driving rain.",
            astrology = "Saturn in Libra",
            numerology = "3",
            element = "Air",
            planet = "Saturn",
            symbology = listOf("Pierced Crimson Heart", "Three Sharp Blades", "Driving Storm Clouds", "Rain of Cleansing"),
            defaultTerms = listOf("Heartbreak", "Grief", "Sorrow", "Release", "Pain")
        ),
        TarotCard(
            name = "Four of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Rest, sanctuary, mental recuperation, contemplation, peaceful pause.",
            reversedMeaning = "Exhaustion, burnout, restlessness, forced isolation, returning to action.",
            description = "A knight's effigy rests peacefully on a tomb with hands in prayer beneath stained glass.",
            astrology = "Jupiter in Libra",
            numerology = "4",
            element = "Air",
            planet = "Jupiter",
            symbology = listOf("Hands in Prayer", "Three Wall Swords & One Tomb Sword", "Stained Glass Sanctuary", "Stone Stillness"),
            defaultTerms = listOf("Rest", "Sanctuary", "Recuperation", "Meditation", "Peace")
        ),
        TarotCard(
            name = "Five of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Hollow victory, unbridled ambition, conflict, ego clash, cutting losses.",
            reversedMeaning = "Desire to reconcile, ending disputes, forgiveness, acknowledging mistakes.",
            description = "A smug victor smiles clutching three swords while defeated rivals walk away weeping into stormy winds.",
            astrology = "Venus in Aquarius",
            numerology = "5",
            element = "Air",
            planet = "Venus",
            symbology = listOf("Three Held Swords & Two on Ground", "Smug Smirk", "Weeping Rivals", "Ragged Storm Clouds"),
            defaultTerms = listOf("Conflict", "Hollow Victory", "Ego", "Loss", "Defeat")
        ),
        TarotCard(
            name = "Six of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Transition, rite of passage, leaving rough waters, gradual healing, journey.",
            reversedMeaning = "Trapped baggage, resisting change, unfinished business, rough travel.",
            description = "A ferryman quietly poles a mother and child across rippled water toward calm distant shores.",
            astrology = "Mercury in Aquarius",
            numerology = "6",
            element = "Air",
            planet = "Mercury",
            symbology = listOf("Six Upright Swords in Boat", "Turbulent Waters Behind, Calm Ahead", "Cloaked Passengers"),
            defaultTerms = listOf("Transition", "Passage", "Healing", "Journey", "Relief")
        ),
        TarotCard(
            name = "Seven of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Stealth, strategy, cunning, resourcefulness, acting discreetly, solo plan.",
            reversedMeaning = "Confession, deceit exposed, coming clean, imposter syndrome, rethink tactics.",
            description = "A solitary figure sneaks away on tiptoe carrying five swords while looking back at the encampment.",
            astrology = "Moon in Aquarius",
            numerology = "7",
            element = "Air",
            planet = "Moon",
            symbology = listOf("Carried Five Swords", "Two Left Swords", "Military Encampment", "Tiptoe Gait"),
            defaultTerms = listOf("Strategy", "Stealth", "Cunning", "Tactics", "Independence")
        ),
        TarotCard(
            name = "Eight of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Self-imposed restriction, mental cage, victim mentality, paralysis of fear.",
            reversedMeaning = "Reclaiming autonomy, seeing open exits, mental liberation, clarity.",
            description = "A blindfolded and loosely bound woman stands surrounded by eight swords in muddy water.",
            astrology = "Jupiter in Gemini",
            numerology = "8",
            element = "Air",
            planet = "Jupiter",
            symbology = listOf("Loose Bindings", "Blindfold", "Enclosing Ring of Eight Swords", "Distant Castle on Hill"),
            defaultTerms = listOf("Imprisonment", "Self-Limiting Beliefs", "Fear", "Liberation", "Perception")
        ),
        TarotCard(
            name = "Nine of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Anxiety, nightmares, overthinking, midnight worry, mental anguish.",
            reversedMeaning = "Release of fear, dawn after dark, seeking help, mental recovery.",
            description = "A figure sits up weeping in bed with face in hands beneath nine hanging swords against blackness.",
            astrology = "Mars in Gemini",
            numerology = "9",
            element = "Air",
            planet = "Mars",
            symbology = listOf("Nine Hanging Blades", "Quilt with Astrological & Rose Motifs", "Head in Hands", "Midnight Darkness"),
            defaultTerms = listOf("Anxiety", "Nightmares", "Overthinking", "Despair", "Awakening")
        ),
        TarotCard(
            name = "Ten of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Rock bottom, painful end, betrayal, final exhaustion, dawn of a new cycle.",
            reversedMeaning = "Surviving the worst, recovery, healing from betrayal, inevitable end.",
            description = "A fallen figure lies on the shore pierced by ten swords, while a golden dawn breaks across the horizon.",
            astrology = "Sun in Gemini",
            numerology = "10",
            element = "Air",
            planet = "Sun",
            symbology = listOf("Ten Piercing Swords", "Black Pitch Sky Above, Golden Dawn Below", "Serene Water", "Red Shroud"),
            defaultTerms = listOf("Ending", "Rock Bottom", "Betrayal", "Dawn", "Renewal")
        ),
        TarotCard(
            name = "Page of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Curiosity, vigilance, quick wit, new intellectual interest, mental agility.",
            reversedMeaning = "Deceit, all talk and no action, cynicism, malicious gossip.",
            description = "An alert youth stands on high ground brandishing a sword with both hands into breezy gusts.",
            astrology = "Earth of Air",
            numerology = "Page",
            element = "Air",
            planet = "Mercury",
            symbology = listOf("Both Hands on Raised Blade", "Wind-blown Trees and Clouds", "Alert Stance", "High Promontory"),
            defaultTerms = listOf("Curiosity", "Vigilance", "Wits", "Honesty", "Agility")
        ),
        TarotCard(
            name = "Knight of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Decisive drive, swift intellect, fearless charge, direct action, ambition.",
            reversedMeaning = "Recklessness, abrasive rudeness, rushed blunders, headstrong folly.",
            description = "A charging knight brandishes his broadsword, hurtling headlong into storm winds atop a swift charger.",
            astrology = "Fire of Air",
            numerology = "Knight",
            element = "Air",
            planet = "Mercury / Mars",
            symbology = listOf("Charging White Warhorse", "Forward Pointed Blade", "Scattered Birds in Wind", "Windblown Cloak"),
            defaultTerms = listOf("Direct Action", "Speed", "Intellect", "Focus", "Ambition")
        ),
        TarotCard(
            name = "Queen of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Clear perception, razor intellect, boundaries, impartial justice, truth.",
            reversedMeaning = "Cold cynicism, bitterness, sharp cruelty, emotional detachment.",
            description = "A poised queen sits upon a cloud-carved stone throne holding her upright sword and welcoming hand.",
            astrology = "Water of Air",
            numerology = "Queen",
            element = "Air",
            planet = "Mercury / Saturn",
            symbology = listOf("Perpendicular Sword of Truth", "Stone Throne with Cherub", "Outstretched Hand", "Lone Bird in Sky"),
            defaultTerms = listOf("Truth", "Perception", "Boundaries", "Clarity", "Justice")
        ),
        TarotCard(
            name = "King of Swords",
            arcana = "Minor",
            suit = "Swords",
            uprightMeaning = "Mastery of mind, ethical authority, legal clarity, rational judgment.",
            reversedMeaning = "Tyranny, manipulation, abuse of intellect, cold calculated injustice.",
            description = "A stern judge sits on a high throne holding an upright sword, draped in robes of heavenly blue and purple.",
            astrology = "Air of Air",
            numerology = "King",
            element = "Air",
            planet = "Mercury / Jupiter",
            symbology = listOf("Upright Sword of Judgment", "Two Angels Carved in Throne", "Robes of Authority", "Serene Sky"),
            defaultTerms = listOf("Authority", "Reason", "Truth", "Judgment", "Integrity")
        ),

        // --- SUIT OF PENTACLES (EARTH) ---
        TarotCard(
            name = "Ace of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Abundance, financial opportunity, tangible manifestation, prosperity.",
            reversedMeaning = "Lost opportunity, financial delay, lack of foresight, over-spending.",
            description = "A divine hand offers a gleaming golden pentacle coin above a lush manicured rose garden.",
            astrology = "Taurus / Virgo / Capricorn",
            numerology = "1",
            element = "Earth",
            planet = "Venus / Saturn",
            symbology = listOf("Golden Coin with Pentagram", "Archway of Lilies & Roses", "Lush Path to Mountains", "Hand in Cloud"),
            defaultTerms = listOf("Manifestation", "Prosperity", "Abundance", "Security", "Opportunity")
        ),
        TarotCard(
            name = "Two of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Balance, adaptability, juggling resources, flexible time management.",
            reversedMeaning = "Over-committed, financial chaos, dropped balls, losing balance.",
            description = "A young juggler effortlessly loops two golden coins inside a green lemniscate infinity band.",
            astrology = "Jupiter in Capricorn",
            numerology = "2",
            element = "Earth",
            planet = "Jupiter",
            symbology = listOf("Green Infinity Lemniscate", "Two Pentacles", "Surging Ships on Waves", "High Pointed Cap"),
            defaultTerms = listOf("Balance", "Adaptability", "Juggling", "Flexibility", "Rhythm")
        ),
        TarotCard(
            name = "Three of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Craftsmanship, teamwork, collaboration, shared expertise, building quality.",
            reversedMeaning = "Ego conflict, poor teamwork, shoddy workmanship, misalignment.",
            description = "A master stonemason consults plans with a monk and architect in a vaulted Gothic cathedral.",
            astrology = "Mars in Capricorn",
            numerology = "3",
            element = "Earth",
            planet = "Mars",
            symbology = listOf("Three Carved Stone Pentacles", "Architectural Blueprint", "Cathedral Archways", "Collaborative Council"),
            defaultTerms = listOf("Craftsmanship", "Teamwork", "Mastery", "Collaboration", "Quality")
        ),
        TarotCard(
            name = "Four of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Security, conservation, guarding wealth, stability, financial boundaries.",
            reversedMeaning = "Greed, hoarding, fear of loss, scarcity mindset, stubborn clinging.",
            description = "A crown-wearing burgher clings tightly to four coins: one on head, one in hands, two underfoot.",
            astrology = "Sun in Capricorn",
            numerology = "4",
            element = "Earth",
            planet = "Sun",
            symbology = listOf("Coins Clutched Tight", "Crown of Earthly Wealth", "City Skyline", "Firm Stance"),
            defaultTerms = listOf("Security", "Stability", "Control", "Conservation", "Possession")
        ),
        TarotCard(
            name = "Five of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Material hardship, feeling left in the cold, temporary lack, seeking shelter.",
            reversedMeaning = "Recovery from financial crisis, finding warmth, spiritual sanctuary.",
            description = "Two impoverished travelers walk through snow past the glowing stained glass window of a warm sanctuary.",
            astrology = "Mercury in Taurus",
            numerology = "5",
            element = "Earth",
            planet = "Mercury",
            symbology = listOf("Glowing Stained Glass Window with Five Pentacles", "Crutches & Snow", "Sanctuary Door Nearby"),
            defaultTerms = listOf("Hardship", "Sanctuary", "Endurance", "Lack", "Recovery")
        ),
        TarotCard(
            name = "Six of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Generosity, charity, sharing wealth, fair distribution, gratitude.",
            reversedMeaning = "One-sided charity, strings attached, debts, unfair power dynamics.",
            description = "A benevolent merchant weighs fair balance scales while distributing gold coins to the needy.",
            astrology = "Moon in Taurus",
            numerology = "6",
            element = "Earth",
            planet = "Moon",
            symbology = listOf("Scales of Balance", "Hand Bestowing Gold", "Grateful Recipients", "Regal Tunic"),
            defaultTerms = listOf("Generosity", "Charity", "Equity", "Balance", "Giving")
        ),
        TarotCard(
            name = "Seven of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Patience, long-term investment, pausing to assess growth, sustainable harvest.",
            reversedMeaning = "Impatience, lack of long-term vision, wasted effort, disappointment.",
            description = "A farmer leans peacefully on his hoe, contemplating seven blossoming golden coins on a heavy vine.",
            astrology = "Saturn in Taurus",
            numerology = "7",
            element = "Earth",
            planet = "Saturn",
            symbology = listOf("Vines Bearing Seven Pentacles", "Resting Farmer on Hoe", "Abundant Crop", "Patience"),
            defaultTerms = listOf("Patience", "Investment", "Assessment", "Growth", "Harvest")
        ),
        TarotCard(
            name = "Eight of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Diligence, apprenticeship, repetitive mastery, dedication, fine craftsmanship.",
            reversedMeaning = "Perfectionism, cutting corners, tedious boredom, lack of ambition.",
            description = "A focused artisan hammers out coins at a wooden bench, with completed coins displayed neatly on a post.",
            astrology = "Sun in Virgo",
            numerology = "8",
            element = "Earth",
            planet = "Sun",
            symbology = listOf("Hammer and Chisel", "Row of Seven Finished Coins", "Workbench", "Distant Town"),
            defaultTerms = listOf("Diligence", "Craft", "Mastery", "Dedication", "Learning")
        ),
        TarotCard(
            name = "Nine of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Self-sufficiency, luxury, elegance, financial independence, refined abundance.",
            reversedMeaning = "Over-investment in material status, feeling unfulfilled, dependence.",
            description = "An aristocratic lady rests gracefully in a sunlit vineyard, with a hooded falcon perched on her gloved hand.",
            astrology = "Venus in Virgo",
            numerology = "9",
            element = "Earth",
            planet = "Venus",
            symbology = listOf("Hooded Hunting Falcon", "Gilded Robes with Sunflowers", "Nine Heavy Coins on Grapevines", "Snail"),
            defaultTerms = listOf("Independence", "Luxury", "Abundance", "Self-Sufficiency", "Elegance")
        ),
        TarotCard(
            name = "Ten of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Legacy, generational wealth, family estate, long-term security, traditions.",
            reversedMeaning = "Family disputes over inheritance, financial loss, broken traditions.",
            description = "Three generations of family and their dogs gather outside an ancestral manor adorned with ten coins.",
            astrology = "Mercury in Virgo",
            numerology = "10",
            element = "Earth",
            planet = "Mercury",
            symbology = listOf("Ten Pentacles Arranged as Tree of Life", "Patriarch & Descendants", "Faithful Dogs", "Ancestral Gateway"),
            defaultTerms = listOf("Legacy", "Inheritance", "Generational Wealth", "Family", "Tradition")
        ),
        TarotCard(
            name = "Page of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Scholarship, manifesting ideas, practical ambition, new study, diligence.",
            reversedMeaning = "Procrastination, lack of follow-through, failed attempts, short-sightedness.",
            description = "A studious young scholar holds a golden pentacle aloft in open green fields, meditating on its potential.",
            astrology = "Earth of Earth",
            numerology = "Page",
            element = "Earth",
            planet = "Saturn",
            symbology = listOf("Gazing at Raised Coin", "Flourishing Meadow & Furrows", "Green Tabard", "Red Chaperon Hat"),
            defaultTerms = listOf("Opportunity", "Study", "Ambition", "Manifestation", "Diligence")
        ),
        TarotCard(
            name = "Knight of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Steadfast reliability, patient routine, duty, disciplined execution, tenacity.",
            reversedMeaning = "Stubborn stagnation, workaholic monotony, unbending narrow-mindedness.",
            description = "A heavy knight sits patiently on a dark draft horse atop plowed fields, holding a solid golden coin.",
            astrology = "Fire of Earth",
            numerology = "Knight",
            element = "Earth",
            planet = "Venus / Saturn",
            symbology = listOf("Heavy Dark Draft Horse", "Ploughed Furrows", "Golden Coin of Substance", "Oak Leaves Plume"),
            defaultTerms = listOf("Reliability", "Discipline", "Tenacity", "Duty", "Routine")
        ),
        TarotCard(
            name = "Queen of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Nurturing abundance, practical care, earth mother, hospitality, prosperity.",
            reversedMeaning = "Neglecting self-care, smothering domestic control, work-life burnout.",
            description = "A serene queen sits on a stone throne carved with beasts and fruit, holding a coin amid nature.",
            astrology = "Water of Earth",
            numerology = "Queen",
            element = "Earth",
            planet = "Venus / Earth",
            symbology = listOf("Coin Held in Lap", "Leaping Rabbit of Fertility", "Fruit and Rose Bower", "Throne of Beasts"),
            defaultTerms = listOf("Nurturing", "Abundance", "Hospitality", "Sensibility", "Practicality")
        ),
        TarotCard(
            name = "King of Pentacles",
            arcana = "Minor",
            suit = "Pentacles",
            uprightMeaning = "Financial empire, master of resources, steadfast security, generosity, mentor.",
            reversedMeaning = "Greed, materialistic obsession, stubborn conservatism, financial corruption.",
            description = "A majestic king draped in grape-patterned robes sits proudly on a bull-carved throne in his courtyard.",
            astrology = "Air of Earth",
            numerology = "King",
            element = "Earth",
            planet = "Venus / Saturn",
            symbology = listOf("Bull Head Carvings (Taurus)", "Grapevine Robes", "Scepter & Golden Coin", "Castle Courtyard"),
            defaultTerms = listOf("Empire", "Security", "Leadership", "Abundance", "Mastery")
        )
    ).mapIndexed { idx, card -> card.copy(id = idx) }

    val cards: List<TarotCard>
        get() = com.example.data.CardAlignmentManager.alignedCards
}
