package com.example.model

data class TarotCard(
    val name: String,
    val arcana: String, // "Major" or "Minor"
    val suit: String?, // "Wands", "Cups", "Swords", "Pentacles", or null for Major
    val uprightMeaning: String,
    val reversedMeaning: String,
    val description: String,
    val astrology: String,
    val numerology: String,
    val element: String,
    val planet: String,
    val symbology: List<String>,
    val defaultTerms: List<String>
)

object TarotData {
    val cards = listOf(
        TarotCard(
            name = "0. The Fool",
            arcana = "Major",
            suit = null,
            uprightMeaning = "New beginnings, innocence, spontaneity, a free spirit.",
            reversedMeaning = "Naivety, foolishness, recklessness, risk-taking.",
            description = "A young traveler stepping off a cliff with complete faith in the universe.",
            astrology = "Aquarius",
            numerology = "0",
            element = "Air",
            planet = "Uranus",
            symbology = listOf("White Dog (Loyalty/Instinct)", "Cliff (Leap of Faith)", "Sun (Vitality)", "Knapsack (Preparedness)"),
            defaultTerms = listOf("Beginnings", "Spontaneity", "Potential", "Innocence", "Leap of Faith")
        ),
        TarotCard(
            name = "I. The Magician",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Manifestation, resourcefulness, power, inspired action.",
            reversedMeaning = "Manipulation, poor planning, untapped talents.",
            description = "A master of elements standing before an altar with tools of creation.",
            astrology = "Gemini / Virgo",
            numerology = "I",
            element = "Air",
            planet = "Mercury",
            symbology = listOf("Infinity Symbol (Eternal Power)", "Wand (Willpower)", "Four Elements (Cups, Pentacles, Swords, Wands)", "Red Roses & White Lilies"),
            defaultTerms = listOf("Manifestation", "Willpower", "Creation", "Skill", "Resourcefulness")
        ),
        TarotCard(
            name = "II. The High Priestess",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Intuition, sacred knowledge, divine feminine, subconscious.",
            reversedMeaning = "Secrets, disconnected intuition, superficiality.",
            description = "A veiled figure seated between pillars of light and darkness.",
            astrology = "Cancer",
            numerology = "II",
            element = "Water",
            planet = "Moon",
            symbology = listOf("Pillars J & B (Dualism)", "Pomegranate Veil (Fertility & Mystery)", "Scroll of Torah", "Crescent Moon"),
            defaultTerms = listOf("Intuition", "Subconscious", "Mystery", "Inner Voice", "Divine Feminine")
        ),
        TarotCard(
            name = "III. The Empress",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Femininity, beauty, nature, nurturing, abundance.",
            reversedMeaning = "Creative block, dependence on others, emptiness.",
            description = "A majestic queen surrounded by golden wheat fields and cascading waterfalls.",
            astrology = "Taurus / Libra",
            numerology = "III",
            element = "Earth",
            planet = "Venus",
            symbology = listOf("Venus Symbol", "Wheat Field (Harvest)", "Star Crown (12 Stars)", "Waterfall & Forest"),
            defaultTerms = listOf("Abundance", "Nurturing", "Nature", "Fertility", "Creativity")
        ),
        TarotCard(
            name = "IV. The Emperor",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Authority, structure, control, father figure, establishment.",
            reversedMeaning = "Tyranny, rigidity, coldness, lack of discipline.",
            description = "A stern ruler seated on a stone throne adorned with ram heads.",
            astrology = "Aries",
            numerology = "IV",
            element = "Fire",
            planet = "Mars",
            symbology = listOf("Ram Heads (Aries/Leadership)", "Stone Throne (Stability)", "Globe of Dominion", "Mountains"),
            defaultTerms = listOf("Authority", "Structure", "Leadership", "Stability", "Control")
        ),
        TarotCard(
            name = "V. The Hierophant",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Spiritual wisdom, religious beliefs, conformity, tradition, institutions.",
            reversedMeaning = "Personal beliefs, rebellion, unorthodox approaches.",
            description = "A spiritual teacher bestowing blessings in a sacred temple.",
            astrology = "Taurus",
            numerology = "V",
            element = "Earth",
            planet = "Venus / Jupiter",
            symbology = listOf("Triple Crown", "Crossed Keys", "Two Acolytes", "Pillars of the Temple"),
            defaultTerms = listOf("Tradition", "Spiritual Wisdom", "Guidance", "Institutions", "Beliefs")
        ),
        TarotCard(
            name = "VI. The Lovers",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Love, harmony, vital relationships, values alignment, choices.",
            reversedMeaning = "Disharmony, imbalance, misaligned values, bad choices.",
            description = "Two souls standing under the blessing of an angelic figure in Eden.",
            astrology = "Gemini",
            numerology = "VI",
            element = "Air",
            planet = "Mercury",
            symbology = listOf("Angel Raphael (Healing)", "Tree of Life & Knowledge", "The Serpent", "Mountain of Ascension"),
            defaultTerms = listOf("Love", "Harmonious Union", "Choices", "Values", "Partnership")
        ),
        TarotCard(
            name = "VII. The Chariot",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Control, willpower, success, action, determination, overcoming obstacles.",
            reversedMeaning = "Lack of control, opposition, directionless wandering.",
            description = "A victorious warrior steering a chariot pulled by sphinxes of will.",
            astrology = "Cancer",
            numerology = "VII",
            element = "Water",
            planet = "Moon",
            symbology = listOf("Black & White Sphinxes (Duality)", "Canopy of Stars", "Wand of Power", "Armor of Protection"),
            defaultTerms = listOf("Victory", "Willpower", "Drive", "Determination", "Focus")
        ),
        TarotCard(
            name = "VIII. Strength",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Courage, compassion, inner power, patience, gentle control.",
            reversedMeaning = "Self-doubt, raw emotion, weakness, lack of confidence.",
            description = "A calm figure gently closing the jaws of a majestic lion.",
            astrology = "Leo",
            numerology = "VIII",
            element = "Fire",
            planet = "Sun",
            symbology = listOf("Infinity Lemniscate", "The Lion (Passion/Ego)", "Garland of Flowers", "Serene Woman"),
            defaultTerms = listOf("Courage", "Compassion", "Inner Strength", "Patience", "Resilience")
        ),
        TarotCard(
            name = "IX. The Hermit",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Soul-searching, introspection, solitude, inner guidance, wisdom.",
            reversedMeaning = "Isolation, loneliness, withdrawal, lost direction.",
            description = "An old sage holding a glowing lantern high on a snowy mountain peak.",
            astrology = "Virgo",
            numerology = "IX",
            element = "Earth",
            planet = "Mercury",
            symbology = listOf("Lantern of Truth (Solomon's Seal)", "Staff of Authority", "Snowy Mountain", "Solitude"),
            defaultTerms = listOf("Introspection", "Solitude", "Inner Guidance", "Wisdom", "Soul-Searching")
        ),
        TarotCard(
            name = "X. Wheel of Fortune",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Good luck, karma, life cycles, destiny, turning point, inevitability.",
            reversedMeaning = "Bad luck, negative cycles, resistance to change.",
            description = "A cosmic wheel turning through epochs with figures of fate ascending and descending.",
            astrology = "Jupiter",
            numerology = "X",
            element = "Fire",
            planet = "Jupiter",
            symbology = listOf("Sphinx of Wisdom", "Anubis & Typhon", "Hebrew Letters (YHWH)", "Four Winged Evangels"),
            defaultTerms = listOf("Destiny", "Karma", "Turning Point", "Cycles", "Fortune")
        ),
        TarotCard(
            name = "XI. Justice",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Fairness, truth, cause and effect, law, clarity, accountability.",
            reversedMeaning = "Dishonesty, unfairness, lack of accountability, bias.",
            description = "An impartial judge holding the scales of truth and a double-edged sword.",
            astrology = "Libra",
            numerology = "XI",
            element = "Air",
            planet = "Venus",
            symbology = listOf("Scales of Balance", "Double-Edged Sword", "Red Cape & Crown", "Pillar of Law"),
            defaultTerms = listOf("Justice", "Truth", "Fairness", "Accountability", "Law")
        ),
        TarotCard(
            name = "XII. The Hanged Man",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Surrender, pause, new perspective, letting go, enlightenment.",
            reversedMeaning = "Stalling, needless sacrifice, fear of sacrifice.",
            description = "A serene figure suspended upside down from a living wooden cross.",
            astrology = "Neptune / Pisces",
            numerology = "XII",
            element = "Water",
            planet = "Neptune",
            symbology = listOf("Halo of Enlightenment", "T-Cross of Living Wood", "Suspended Posture", "Serene Expression"),
            defaultTerms = listOf("Surrender", "New Perspective", "Release", "Pause", "Enlightenment")
        ),
        TarotCard(
            name = "XIII. Death",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Transformation, endings, transition, rebirth, shedding the old.",
            reversedMeaning = "Resistance to change, stagnation, fear of inevitable endings.",
            description = "An armored skeleton riding a white horse across a threshold of sun and dawn.",
            astrology = "Scorpio",
            numerology = "XIII",
            element = "Water",
            planet = "Pluto",
            symbology = listOf("Armored Skeleton", "White Horse", "Rising Sun between Towers", "Mystic Rose Flag"),
            defaultTerms = listOf("Transformation", "Rebirth", "Endings", "Transition", "Renewal")
        ),
        TarotCard(
            name = "XIV. Temperance",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Balance, moderation, patience, purpose, divine timing, harmony.",
            reversedMeaning = "Imbalance, excess, clashing energies, lack of patience.",
            description = "An angelic being pouring fluid between two golden chalices with perfect balance.",
            astrology = "Sagittarius",
            numerology = "XIV",
            element = "Fire",
            planet = "Jupiter",
            symbology = listOf("Angel with Wings", "Two Golden Chalices", "One Foot in Water, One on Land", "Path to Mountains"),
            defaultTerms = listOf("Balance", "Moderation", "Harmony", "Patience", "Alchemy")
        ),
        TarotCard(
            name = "XV. The Devil",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Shadow self, attachment, addiction, restriction, materialism.",
            reversedMeaning = "Freedom, reclaiming power, overcoming addiction, release.",
            description = "Bound figures standing before a horned deity of worldly illusion.",
            astrology = "Capricorn",
            numerology = "XV",
            element = "Earth",
            planet = "Saturn",
            symbology = listOf("Baphomet / Horned God", "Loose Chains on Figures", "Inverted Pentagram", "Torch of Illusions"),
            defaultTerms = listOf("Shadow Self", "Attachment", "Bondage", "Materialism", "Liberation")
        ),
        TarotCard(
            name = "XVI. The Tower",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Sudden change, upheaval, revelation, awakening, breaking illusions.",
            reversedMeaning = "Disaster avoided, delayed trauma, fear of suffering.",
            description = "Lightning striking a stone tower as flames burst from the windows.",
            astrology = "Mars",
            numerology = "XVI",
            element = "Fire",
            planet = "Mars",
            symbology = listOf("Lightning Bolt (Divine Strike)", "Falling Crown", "Burning Tower", "Yot Flames"),
            defaultTerms = listOf("Upheaval", "Revelation", "Sudden Change", "Awakening", "Breakthrough")
        ),
        TarotCard(
            name = "XVII. The Star",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Hope, faith, purpose, renewal, inspiration, spiritual blessing.",
            reversedMeaning = "Despair, lack of faith, discouragement, pessimism.",
            description = "A celestial maiden pouring healing waters into a serene starlit pool.",
            astrology = "Aquarius",
            numerology = "XVII",
            element = "Air",
            planet = "Uranus",
            symbology = listOf("8-Pointed Star of Venus", "Two Urns of Water", "Naked Figure (Vulnerability)", "Ibis Bird"),
            defaultTerms = listOf("Hope", "Faith", "Inspiration", "Renewal", "Healing")
        ),
        TarotCard(
            name = "XVIII. The Moon",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Illusion, fear, anxiety, subconscious, intuition, dreams, uncertainty.",
            reversedMeaning = "Release of fear, repressed emotion surfacing, clarity dawning.",
            description = "A mystical night landscape illuminated by a crescent moon and howling wolves.",
            astrology = "Pisces",
            numerology = "XVIII",
            element = "Water",
            planet = "Neptune",
            symbology = listOf("Crescent Moon with Face", "Dog and Wolf (Tame/Wild Nature)", "Crawling Crayfish", "Two Towers"),
            defaultTerms = listOf("Illusion", "Dreams", "Subconscious", "Fear", "Intuition")
        ),
        TarotCard(
            name = "XIX. The Sun",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Joy, success, celebration, vitality, positivity, warmth, clarity.",
            reversedMeaning = "Temporary sadness, overly optimistic view, clouded joy.",
            description = "A radiant golden sun shining down upon a joyful child riding a white horse.",
            astrology = "Sun",
            numerology = "XIX",
            element = "Fire",
            planet = "Sun",
            symbology = listOf("Radiant Sun with Face", "Naked Child (Innocence)", "White Horse of Purity", "Sunflower Garden"),
            defaultTerms = listOf("Joy", "Success", "Vitality", "Optimism", "Clarity")
        ),
        TarotCard(
            name = "XX. Judgement",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Rebirth, inner calling, absolution, awakening, reckoning, forgiveness.",
            reversedMeaning = "Self-doubt, harsh self-judgment, ignoring the call.",
            description = "An angelic trumpet sounding as figures rise joyfully from earthly graves.",
            astrology = "Pluto",
            numerology = "XX",
            element = "Fire",
            planet = "Pluto",
            symbology = listOf("Archangel Gabriel", "Trumpet of Awakening", "Rising Figures from Coffins", "Mountains of Eternity"),
            defaultTerms = listOf("Rebirth", "Awakening", "Calling", "Absolution", "Judgment")
        ),
        TarotCard(
            name = "XXI. The World",
            arcana = "Major",
            suit = null,
            uprightMeaning = "Completion, accomplishment, travel, wholeness, fulfillment, unity.",
            reversedMeaning = "Lack of closure, unfinished business, delays in success.",
            description = "A dancing figure framed by a laurel wreath surrounded by the four cosmic guardians.",
            astrology = "Saturn",
            numerology = "XXI",
            element = "Earth",
            planet = "Saturn",
            symbology = listOf("Laurel Wreath of Victory", "Dancing Hermaphrodite", "Four Evangelists (Bull, Lion, Eagle, Angel)", "Wands of Power"),
            defaultTerms = listOf("Completion", "Wholeness", "Achievement", "Fulfillment", "Unity")
        )
    )
}
